---
title: >
  Flavors of the pharmaverse
subtitle: "[https://posit-conf-2024.github.io/pharmaverse/](https://posit-conf-2024.github.io/pharmaverse/)"
author:
  - name: Daniel D. Sjoberg
    affiliations:
      - name: Genentech
  - name: Becca Krouse
    affiliations:
      - name: GSK
  - name: Daniel D. Sjoberg
    affiliations:
      - name: Genentech
  - name: Ellis Hughes
    affiliations:
      - name: Pharmaceutical industry
  - name: Andrew Bates
    affiliations:
      - name: Atorus Research
  - name: Casey Aguilar-Gervase
    affiliations:
      - name: Atorus Research
description: >
  High level overview of the scope and tools available within the pharmaverse for the clinical pipeline, including tools for ADaM data set curation, creating Analysis Results Data Sets, and TLGs.
categories: [R, pharma]
---

# Description

Over the past 4 years, the pharmaverse was created and has blossomed into a booming community of organizations and package developers aimed at supporting R development with focus on the clinical reporting pipeline.
Even within a world as standardized as regulatory submissions, organizations still tend to have sometimes vastly different requirements within their own processes.

In this workshop, we’ll give a high level overview of the scope and tools available within the pharmaverse for the clinical pipeline, including tools for ADaM data set curation, creating Analysis Results Data Sets, and TLGs.
To help attendees understand how there are different paradigms and pathways through the pharmaverse, we’ll take a tour through two to three different strategies available to support table, listing, and figure creation.
Attendees of this workshop will walk away with an understanding of how the pharmaverse can help their organization and where they can look to learn more about the right tools to support their needs.

# Instructor(s)

|     |     |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
|-------------|-------------|-----------------------------------------------|
|     |     | [**Daniel D. Sjoberg**](https://www.danieldsjoberg.com/) (he/him) is a Senior Principal Data Scientist at Genentech. Previously, he was a Lead Data Science Manager at the Prostate Cancer Clinical Trials Consortium, and a Senior Biostatistician at Memorial Sloan Kettering Cancer Center in New York City. He enjoys R package development, creating many packages available on [CRAN](https://cran.r-project.org/web/packages/), [R-Universe](https://ddsjoberg.r-universe.dev/ui#packages), and [GitHub](https://github.com/ddsjoberg). He’s a co-organizer of [rainbowR](https://rainbowr.netlify.app/) (a community that supports, promotes and connects LGBTQ+ people who code in the R language) and of the [R Medicine Conference](https://rconsortium.github.io/RMedicine_website/). His research interests include adaptive methods in clinical trials, precision medicine, and predictive modeling. Daniel is the winner of the 2021 American Statistical Association (ASA) Innovation in Statistical Programming and Analytics award. |
|     |     | **Becca Krouse** is a data scientist in GSK’s Statistics and Data Science Innovation Hub. A biostatistician by training, she has experience spanning 13+ years in the field of clinical research and specializes in developing R-based tools.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
|     |     | **Ellis Hughes** is a Data Science Leader and has worked in the pharmaceutical industry for almost a decade. He focuses on how organizations can use R and take open source approaches to improve processes and solve problems. During his free time he organizes the Seattle UseR group, the Cascadia R Conference, and hosts a weekly R screencast, TidyX, to explain data science concepts.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
|     |     | **Andrew Bates** Andrew is a Data Solutions Engineer at Atorus Research where he builds tools that enable people to solve their data problems. He specializes in R and its intersection with web technologies.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
|     |     | **Casey Aguilar-Gervase** is a Senior Data Visualization Engineer at Atorus. Casey enjoys combining the art of design with clinical programming in R to create innovative Shiny applications. With a strong background in both disciplines, Casey is passionate about pushing the boundaries of Shiny to develop user-friendly, data-driven solutions that meet technical requirements and provide an exceptional user experience.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |

: {tbl-colwidths="\[25,5,70\]"}
